In [1]:
import glob
import pandas as pd

In [4]:
# filenames_capture = glob.glob(f'/home/igavier_umass_edu/Documents/Neuromorphic-IMU/results/spike_encoder_neurobench_capture24_*_*.csv')
# filenames_wisdm = glob.glob(f'/home/igavier_umass_edu/Documents/Neuromorphic-IMU/results/spike_encoder_neurobench_wisdm_*_*.csv')
filenames_realworld = glob.glob(f'/home/igavier_umass_edu/Documents/Neuromorphic-IMU/results/spike_encoder_neurobench_realworld_*_*.csv')
# filenames_mhealth = glob.glob(f'/home/igavier_umass_edu/Documents/Neuromorphic-IMU/results/spike_encoder_neurobench_mhealth_*_*.csv')

# df_capture = pd.concat((pd.read_csv(f, index_col=0) for f in filenames_capture), ignore_index=True)
# df_wisdm = pd.concat((pd.read_csv(f, index_col=0) for f in filenames_wisdm), ignore_index=True)
df_realworld = pd.concat((pd.read_csv(f, index_col=0) for f in filenames_realworld), ignore_index=True)
# df_mhealth = pd.concat((pd.read_csv(f, index_col=0) for f in filenames_mhealth), ignore_index=True)

# df_capture['dataset'] = 'capture24'
# df_wisdm['dataset'] = 'wisdm'
df_realworld['dataset'] = 'realworld'
# df_mhealth['dataset'] = 'mhealth'

df = pd.concat([df_realworld], ignore_index=True)

df

,subject_ID,method,duration,nrmse,snr,spks,snrperspks,dataset
0,0.0,BSA,8459.96875,0.298803,0.121047,0.439190,0.275614,realworld
1,0.0,Burst,8459.96875,0.307248,0.000004,0.000473,0.008974,realworld
2,0.0,HSA,8459.96875,0.300664,0.094091,0.662319,0.142063,realworld
3,0.0,MHSA,8459.96875,0.307226,0.000320,0.000173,1.843528,realworld
4,0.0,MW,8459.96875,13398.228003,-46.395575,33.090981,-1.402061,realworld
...,...,...,...,...,...,...,...,...
177,13.0,SF,8859.96875,0.648811,-2.842100,5.944618,-0.478096,realworld
178,13.0,TBR,8859.96875,2415.750326,-38.551438,33.019913,-1.167521,realworld
179,13.0,TTFS,8859.96875,0.394188,-0.677951,12.005084,-0.056472,realworld
180,NaN,xylo,8659.93750,0.077833,3.378667,26.785836,0.126136,realworld
181,13.0,ZCSF,8859.96875,269.445123,-29.025621,10.558269,-2.749089,realworld

In [5]:
df['sparsity'] = 100 * (1 - df['spks'] / 64)
df[df.dataset == 'realworld'].groupby(['dataset', 'method']).agg(['mean', 'std', 'count'])[['snr', 'spks']]

                         snr                       spks
                        mean       std count       mean       std count
dataset   method
realworld BSA      -0.182788  0.201532    14   2.633071  1.055638    14
          Burst    -0.494298  0.199455    14   3.714333  1.068922    14
          HSA       0.082075  0.067981    14   0.552051  0.279029    14
          MHSA      0.073447  0.066905    14   0.627847  0.293177    14
          MW      -44.522721  2.695566    14  32.028166  1.894261    14
          NIMU      5.350155  0.320084    12  13.930648  0.710041    12
          Phase    -4.584562  0.585995    13  10.501246  0.083846    13
          Poisson  -1.313454  0.430113    14   3.602301  0.418565    14
          SF       -2.806831  0.420287    14   7.221558  1.060021    14
          TBR     -35.858559  2.466149    14  35.525723  2.646092    14
          TTFS     -0.556798  0.306339    14  11.959552  0.054326    14
          ZCSF    -30.595773  2.249815    14  13.006119  1.537014    14
          nimu      5.345636  0.304967     2   1.423752  0.070356     2
          xylo      2.971645  0.264009    14  29.690633  1.589701    14